//
//  ETStyleKit.h
//  EtsySearch
//
//  Created by Steph Sharp on 16/02/2016.
//  Copyright (c) 2016 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface ETStyleKit : NSObject

// Drawing Methods
+ (void)drawArmchairIconWithRect: (CGRect)rect;
+ (void)drawTeaIconWithRect: (CGRect)rect;
+ (void)drawShoeIconWithRect: (CGRect)rect;
+ (void)drawRingIconWithRect: (CGRect)rect;
+ (void)drawLampIconWithRect: (CGRect)rect;
+ (void)drawGiftIconWithRect: (CGRect)rect;
+ (void)drawGlassesIconWithRect: (CGRect)rect;
+ (void)drawBagIconWithRect: (CGRect)rect;
+ (void)drawRadioIconWithRect: (CGRect)rect;
+ (void)drawCoatIconWithRect: (CGRect)rect;
+ (void)drawKnittingIconWithRect: (CGRect)rect;
+ (void)drawWatchIconWithRect: (CGRect)rect;
+ (void)drawDressIconWithRect: (CGRect)rect;
+ (void)drawBuffetIconWithRect: (CGRect)rect;
+ (void)drawBowtieIconWithRect: (CGRect)rect;
+ (void)drawPaintingIconWithRect: (CGRect)rect;

@end
